apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-routes
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: platform-admins
  source:
    repoURL: https://github.com/beckjim/xxx-gitops
    targetRevision: main
    path: platform/routes/base
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
