# Usage:
#   kind create cluster --config xxx.yaml --wait 120s --name xxx
#

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# name is set by kind create cluser --name flag 
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            "enable-admission-plugins": "NodeRestriction,PodSecurity"
    # Map ports for NodePort services
    extraPortMappings:
      - containerPort: 30001  
        hostPort: 30001
        protocol: TCP
  - role: worker
# Networking defaults to kindnet CNI
