apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: platform-admins
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 88.1.5
    helm:
      releaseName: kube-prometheus-stack
      values: |
        prometheus:
          service:
            type: ClusterIP
          prometheusSpec:
            retention: 1d
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false

        alertmanager:
          enabled: false

        grafana:
          enabled: true
          adminPassword: admin
          service:
            type: ClusterIP
          additionalDataSources:
            - name: Loki
              type: loki
              access: proxy
              url: http://loki.monitoring.svc.cluster.local:31000
              isDefault: false
              jsonData:
                maxLines: 1000

        kubeStateMetrics:
          enabled: true

        nodeExporter:
          enabled: true

        defaultRules:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
